name: Qase to Github
on:
  workflow_dispatch:
    inputs:
      qase_api_base_url:
        description: 'Qase API URL'
        required: true
      qase_report:
        description: 'Enabled/disabled reporting to Qase'
        required: true
      qase_project_code:
        description: 'Qase project code'
        required: true
      qase_run_id:
        description: 'Qase Run ID'
        required: true
      qase_run_complete:
        description: 'Qase Run autocomplete'
        required: true
env:
  QASE_API_BASE_URL: ${{ inputs.qase_api_base_url }}
  QASE_TESTOPS_PROJECT: ${{ inputs.qase_project_code }}
  QASE_TESTOPS_RUN_ID: ${{ inputs.qase_run_id }}
  QASE_TESTOPS_RUN_COMPLETE: true
  QASE_DEBUG: true
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_TESTOPS_API_TOKEN }}
  QASE_TESTOPS_PLAN_ID: 5
  

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: cskmnrpt/qase-link-run@v2

      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Install dependencies
        run: |
          npm install
  
      - name: Run Playwright tests
        env:
          QASE_TESTOPS_PLAN_ID: 5 
          QASE_DEBUG: true
          QASE_TESTOPS_RUN_TITLE: "Karan auto run"
          QASE_MODE: "testops"
          
        run: |
          npx playwright test
